### ISSUE TITLE
Question regarding source of WTFPLv3

### ISSUE THREAD

**Issue by benlk** [sirkris/System-47-Delay-Loader-for-Multiple-Monitors#1]
https://github.com/sirkris/System-47-Delay-Loader-for-Multiple-Monitors/blob/5b1dc5e1bcda70d370217f92de95a7d89c7e4a8d/WTFPLv3.txt#L1-L5

I collect [a list of odd software licenses](https://github.com/benlk/misc-licenses), and @DonaldTsang included your use of the WTFPLv3 as a reference for the existence of the WTFPLv3: https://github.com/benlk/misc-licenses/issues/5
 
The version of the WTFPL that I'm familiar with is version 2: http://www.wtfpl.net/about/

When you chose to use the WTFPLv3, where did you find the v3 text? I'm looking for a canonical source that could be added to the list.

**Comment by benlk** [comment]
Wait, I'm a dummy. *You* are Kris Craig.

Would you mind putting your version of the WTFPL into a separate repository, so that I can link to it as a canonical source that credits you?

**Comment by sirkris** [comment]
That's a good idea!  I also went ahead and included previous versions of the WTFPL in the repo, as well.  Here's a direct link to the canonical source as requested:

https://raw.githubusercontent.com/sirkris/WTFPL/master/WTFPL.md

While you're at it, you might want to consider updating the [Wikipedia article](https://en.wikipedia.org/wiki/WTFPL) on the WTFPL to include the latest version.  I can't because I'm the author so it'd be a conflict of interest.

**Comment by DonaldTsang** [comment]
@sirkris Nice! I like how WTFPL is getting updated.

**Comment by benlk** [comment]
Thanks!

**Comment by benlk** [comment]
@sirkris if you want, you could reach out to the WTFPL maintainer at contact@wtfpl.net and get this modification officially listed.
